### ISSUE TITLE
Compatibility with AntiCheats (AntiDLL & Little Anti-Cheat)

### ISSUE THREAD

**Issue by crashzk** [DJPlaya/Cheat-Acid#2]
I would like to know how compatibility with AC [AntiDLL](https://github.com/JDW1337/AntiDLL) & [Little Anti-Cheat](https://github.com/J-Tanzanite/Little-Anti- Cheat).

I ask because I currently use both and so far without compatibility problems and I am enjoying the results. But I'm looking for a AC that supports Anti-WallHack, blocking the use of wallhack on servers.

Does your version have this feature, Anti-WallHack? Can I use it without compatibility issues?

**Comment by DJPlaya** [comment]
Hello,
Cheat-Acid has a long way to go before it is usable, and KACR has only very basic detection mechanisms.
AntiDLL can be used with most other ACs, but i cant say how effective it still is.
L-AC is probably the best main AC currently, but you wont find an easy implementations of Anti-Wallhacking solutions. 
Your best bet is to block all potential information leaks one by one, like randomizing sound locations a bit, you can find that in SMAC or CowAC for example.
CSGO also has a basic system to prevent leak of data to the enemy team based on vision, but it dosent work flawlessly, and sadly [Shadowkeeper](https://github.com/87andrewh/CornerCullingSourceEngine) isent in-dev anymore.
You may want to look out for Hotguard AC or however the Project is currently called if you are looking for a solution with a pricetag, it performed the best in my last tests with V3.2 a while ago.

**Comment by crashzk** [comment]
I understand, thank you.

Like ciotu, the [Shadowkeeper](https://github.com/87andrewh/CornerCullingSourceEngine) for his project development.

Hotguard AC researched a little, many complaints from users and such. Anyway, for now I'll research further and thanks for the information.
